// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2CwkgLgKzSYaxMnjAc-q99hBgqWMepoc',
    appId: '1:720483298963:web:3348e3047b809e256da766',
    messagingSenderId: '720483298963',
    projectId: 'fir-setup-cdde6',
    authDomain: 'fir-setup-cdde6.firebaseapp.com',
    storageBucket: 'fir-setup-cdde6.appspot.com',
    measurementId: 'G-V51RYWC2JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVc9zRLxa5h3hgQV2qbHeR2RsMBZJHEGA',
    appId: '1:720483298963:android:3c3112d703bc31636da766',
    messagingSenderId: '720483298963',
    projectId: 'fir-setup-cdde6',
    storageBucket: 'fir-setup-cdde6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQOyzjZt0jkZoNyb8FcFkIalZYPsNxHV8',
    appId: '1:720483298963:ios:d364c7a91bf7bf856da766',
    messagingSenderId: '720483298963',
    projectId: 'fir-setup-cdde6',
    storageBucket: 'fir-setup-cdde6.appspot.com',
    iosClientId: '720483298963-8m8udrutje2bglauslidsjlr24jrdm8u.apps.googleusercontent.com',
    iosBundleId: 'com.example.webviewgesture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQOyzjZt0jkZoNyb8FcFkIalZYPsNxHV8',
    appId: '1:720483298963:ios:a2ede9e8aa5f3c256da766',
    messagingSenderId: '720483298963',
    projectId: 'fir-setup-cdde6',
    storageBucket: 'fir-setup-cdde6.appspot.com',
    iosClientId: '720483298963-qd0mmaoq69dqea6ko79kbootgojclsfo.apps.googleusercontent.com',
    iosBundleId: 'com.example.webviewgesture.RunnerTests',
  );
}
